# Generated by Django 5.0.2 on 2024-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0014_hrhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Mob', models.CharField(max_length=10, null=True)),
                ('Address', models.CharField(max_length=1000, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Course', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('regDte', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cu_user',
            name='Address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
