# Generated by Django 5.0.2 on 2024-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0016_tutorhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorhistory',
            name='tutortype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
