# Generated by Django 5.0.2 on 2024-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0018_studenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
