# Generated by Django 5.0.2 on 2024-03-09 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0019_alter_studenthistory_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
